### ISSUE TITLE
FluidBottomNavigation-android does not support androidx

### ISSUE THREAD

**Issue by Mikadorimune** [10clouds/FluidBottomNavigation-android#11]
Is there any way to use this with androidx integration?

**Comment by jakubjodelka** [comment]
Yes, i've just update library to AndroidX.
Please update version to the newest one: https://github.com/10clouds/FluidBottomNavigation-android/releases/tag/1.2

**Comment by CappuChinoAssassino** [comment]
Thanks! I really appreciate it!
