### ISSUE TITLE
Animation stuttering when switching between tabs fastly

### ISSUE THREAD

**Issue by rixspi** [10clouds/FluidBottomNavigation-android#4]
![animation-stuttering](https://user-images.githubusercontent.com/9039721/42878846-cdefd7b2-8a8e-11e8-959d-3a38cf0e34f3.gif)

Device: OnePlus 3T
System: 8.0.0 (reproducible on every emulator tested api 25,26,27)

Possible solution: 
Deselect animation should start only after select animation or somehow blend animation to start from another state than selected/deselected

**Comment by praveenvishal** [comment]
Did you find the solution for this bug

**Comment by jakubjodelka** [comment]
> Did you find the solution for this bug

We can't fix this in a simple way with the current code. Unfortunately, we're not gonna solve this problem at the moment.
