### ISSUE TITLE
Gradle fail

### ISSUE THREAD

**Issue by Nicolas99-9** [10clouds/FluidBottomNavigation-android#6]
I tried to add the library to my project:

my gradle file is like that:

`	apply plugin: 'com.android.application'

	android {
		compileSdkVersion 27
		defaultConfig {
			applicationId "com.package.myAppname"
			minSdkVersion 15
			targetSdkVersion 27
			versionCode 1
			versionName "1.0"
			testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
		}
		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			}
		}
	}

	dependencies {
		implementation fileTree(dir: 'libs', include: ['*.jar'])
		implementation 'com.android.support:appcompat-v7:27.1.1'
		implementation 'com.android.support.constraint:constraint-layout:1.1.3'
		implementation 'com.tenclouds.fluidbottomnavigation:fluid-bottom-navigation:1.1'
		testImplementation 'junit:junit:4.12'
		androidTestImplementation 'com.android.support.test:runner:1.0.2'
		androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

	}
`

but I have this message:
Failed to resolve: com.tenclouds

Any suggestion ?

**Comment by jakubjodelka** [comment]
You need add 'jcenter' to repositories in build.gradle.

You can add it in your project build.gradle file:
```
allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
or in module build.gradle
```
repositories {
    google()
    jcenter()
}
```

**Comment by Nicolas99-9** [comment]
I added it:
but I still have the problem:

`	apply plugin: 'com.android.application'

	android {
		compileSdkVersion 27
		defaultConfig {
			applicationId "com.package.myAppname"
			minSdkVersion 19
			targetSdkVersion 27
			versionCode 1
			versionName "1.0"
			testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
		}
		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			}
		}
	}
	repositories {
		maven {
			url "https://jitpack.io"
		}
		jcenter()
	}
	dependencies {
		implementation fileTree(dir: 'libs', include: ['*.jar'])
		implementation 'com.android.support:appcompat-v7:27.1.1'
		implementation 'com.android.support.constraint:constraint-layout:1.1.3'
		testImplementation 'junit:junit:4.12'
		androidTestImplementation 'com.android.support.test:runner:1.0.2'
		androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
		implementation 'com.tenclouds.fluidbottomnavigation:fluid-bottom-navigation:1.1'

	}
`

**Comment by amirparsa1991** [comment]
hello jakubjodelka

build.gradle for Project

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
ext.kotlin_version = '1.2.71'
repositories {
google()
jcenter()
}
dependencies {
classpath 'com.android.tools.build:gradle:3.2.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}

}

allprojects {
repositories {
google()
jcenter()
mavenCentral()

}

}

task clean(type: Delete) {
delete rootProject.buildDir
}

build.gradle for Module

apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
compileSdkVersion 28
defaultConfig {
applicationId "com.gcm.moradi.pivot"
minSdkVersion 19
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}
}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support.constraint:constraint-layout:1.1.3'
testImplementation 'junit:junit:4.12'
androidTestImplementation 'com.android.support.testrunning_man1.0.2'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

//Design Library
implementation 'com.android.support:design:28.0.0'

//Library
implementation 'com.tenclouds.fluidbottomnavigation:fluid-bottom-navigation:1.1'

}

and below error when a synce project

Failed to resolve: com.tenclouds.fluidbottomnavigation:fluid-bottom-navigation:1.1
Show in File
Show in Project Structure dialog

**Comment by jonrysimbolon** [comment]
same here

**Comment by alfikr** [comment]
I found  'com.tenclouds:fluid-bottom-navigation:1.1' on maven central but no FluidBottomNavigation class on this library

**Comment by farahfarah1** [comment]
i have the same problem how can i solve it ?

**Comment by jakubjodelka** [comment]
@Nicolas99-9 @jonrysimbolon @alfikr @farahfarah1 
Hi. There was a problem with library on maven repository.
Please update library version to the newest one using `jitpack.io` repository as it's described in README file.
The newest library version: https://github.com/10clouds/FluidBottomNavigation-android/releases/tag/1.2
