### ISSUE TITLE
Warning from Android Studio, 

### ISSUE THREAD

**Issue by marcelogdl** [10clouds/FluidBottomNavigation-android#9]
I would love to be able to use it in an Android project but when compiling in Android Studio I got this Warning message: 
"API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()' . It will be removed at the end of 2019" 

Do you think you might upload a newer version? Cause if so I would be so grateful!
Thanks so much!

**Comment by jakubjodelka** [comment]
Warning fixed after delete old distribution way. 
Please update version to the newest one: https://github.com/10clouds/FluidBottomNavigation-android/releases/tag/1.2
